# Generated by Django 2.1 on 2018-08-17 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0002_auto_20180817_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratica',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pratiche.Agente'),
        ),
    ]
