# Generated by Django 2.1 on 2018-08-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agente',
            name='matricola',
        ),
        migrations.AddField(
            model_name='agente',
            name='caratt',
            field=models.CharField(default='', max_length=7),
        ),
    ]
